const storiesCommentTypes =  {
	STORIES_LOAD_COMMENTS_START : "STORIES_LOAD_COMMENTS_START",
	STORIES_LOAD_COMMENTS_SUCCESS: "STORIES_LOAD_COMMENTS_SUCCESS",
	STORIES_LOAD_COMMENTS_ERROR: "STORIES_LOAD_COMMENTS_ERROR",
};

export default storiesCommentTypes;