const REGISTER_LOGIN_TYPES =  {
	LOGIN_USER_LOADING : "LOGIN_USER_LOADING",
    LOGIN_USER_FAIL: "LOGIN_USER_FAIL",
    LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
    LOGOUT_USER: "LOGOUT_USER",
	REGISTER_USER_LOADING: "REGISTER_USER_LOADING",
    REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
    REGISTER_USER_FAIL: "REGISTER_USER_FAIL"
};

export default REGISTER_LOGIN_TYPES;